# Generated by Django 4.0.4 on 2022-05-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата поступления')),
                ('unit', models.CharField(max_length=128, verbose_name='Единица измерения')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Цена')),
                ('vendor', models.CharField(max_length=128, verbose_name='Имя поставщика')),
            ],
        ),
    ]
