# Generated by Django 4.0.4 on 2022-06-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('date', models.DateField(verbose_name='дата поступления')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='цена')),
                ('unit', models.IntegerField(choices=[(1, 'шт.'), (2, 'кг.')], verbose_name='единица измерения')),
                ('provider', models.CharField(blank=True, max_length=256, verbose_name='поставщик')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
